# ??springboot?????
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


# Mybatis?mapper.xml????? ???????????
# ???classpath???

# classpath*??????classpath ?????????????????????jar?????????
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml